name: RecipeAutoSync
version: 1.0.0
main: io.github.recipesync.RecipeAutoSync
api-version: "1.20"
description: Automatically sync server recipes to players with Folia support
author: Highrii
website: https://github.com/Highrii/RecipeAutoSync

# Folia 支持配置
folia-supported: true
libraries: []
load: POSTWORLD

commands:
  recipesync:
    description: Reload server recipes
    usage: /<command>
    permission: recipesync.reload

permissions:
  recipesync.reload:
    description: Allows reloading of server recipes
    default: op
